---
- name: Installing docker
  shell: |
    sudo yum update -y
    sudo yum install -y git-all
    sudo amazon-linux-extras install -y docker
    sudo yum install -y docker

- name: Adding ec2-user to sudo group and starting docker
  shell: |
    sudo usermod -a -G docker ec2-user
    sudo service docker start

- name: verifying docker installation
  become: true
  shell: |
    docker info

#mycirclecitoken - 9b7da48e0f98fa971e5cb626c274308605278138
