---
- name: "configuration play."
  hosts: docker
  user: ec2-user
  gather_facts: true
  vars:
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        delay: 10
        timeout: 600
    - name: getting information from remote host
      debug:
        msg: "{{ ansible_env }}"

  roles:
    - configure-docker
    - build-by-lint
    - configure-kubernetes