---
- name: Creates directory
  file:
    path: '~/{{ envname }}'
    state: directory

- name: copying app app.py file
  copy:
    src: app.py
    dest: '~/'

- name: copying app Dockerfile file
  copy:
    src: Dockerfile
    dest: '~/'

- name: copying app requirements.txt file
  copy:
    src: requirements.txt
    dest: '~/'

- name: copying app Makefile file
  copy:
    src: Makefile
    dest: '~/'

- name: copying app Makefile file
  copy:
    src: model_data
    dest: '~/{{ envname }}/'

- name: Setting virtualenv and installing hadolint
#  become: true
  shell: |
    sudo chmod ugo+rw app.py Dockerfile requirements.txt Makefile
    sed -i 's/_envToSet_/{{ envname }}/g' Makefile
    make setup
    source ".{{ envname }}/bin/activate"
    make install lint
# python3 -m venv "{{ envname }}"
# source "{{ envname }}/bin/activate"
# cd "{{ envname }}"
# sudo chmod ugo+rw app.py Dockerfile requirements.txt Makefile
# sed -i 's/_envToSet_/{{ envname }}/g' Makefile
# make install
# # Install hadolint
# sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
# sudo chmod +x /bin/hadolint

