---
- name: Creates directory
  file:
    path: '~/{{ envname }}'
    state: directory

- name: copying app app.py file
  copy:
    src: app.py
    dest: '~/{{ envname }}/app.py'

- name: copying app Dockerfile file
  copy:
    src: Dockerfile
    dest: '~/{{ envname }}/Dockerfile'

- name: copying app requirements.txt file
  copy:
    src: requirements.txt
    dest: '~/{{ envname }}/requirements.txt'

- name: copying app Makefile file
  copy:
    src: Makefile
    dest: '~/{{ envname }}/Makefile'

- name: Setting virtualenv and installing hadolint
#  become: true
  shell: |
    python3 -m venv "{{ envname }}"
    source "{{ envname }}/bin/activate"
    cd "{{ envname }}"
    sudo chmod ugo+rw app.py Dockerfile requirements.txt Makefile
    sed -i 's/_envToSet_/{{ envname }}/g' Makefile
    make install
    # Install hadolint
    sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
    sudo chmod +x /bin/hadolint

- name: Installing circleci CLI
#become: true
  shell: |
    sudo curl -o /usr/local/bin/circleci https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci && sudo chmod +x /usr/local/bin/circleci
    sudo setfacl --modify user:ec2-user:rw /var/run/docker.sock
    sudo setfacl --modify user:ec2-user:rwx /usr/local/bin/circleci
