---
- name: copying app  file
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: 0774
  with_items:
    - run_docker.sh
    - upload_docker.sh

- name: Creates directory
  file:
    path: '~/{{ envname }}'
    state: directory

- name: copying app app.py file
  copy:
    src: app.py
    dest: '~/'

- name: copying app Dockerfile file
  copy:
    src: Dockerfile
    dest: '~/'

- name: copying app requirements.txt file
  copy:
    src: requirements.txt
    dest: '~/'

- name: copying app Makefile file
  copy:
    src: Makefile
    dest: '~/'

- name: copying app Makefile file
  copy:
    src: model_data
    dest: '~/'

- name: Setting venv, installing hadolint, runnint on docker
#  become: true
  shell: |
    echo {{ dockhub }} > my_password.txt
    sudo chmod ugo+rw app.py Dockerfile requirements.txt Makefile
    sed -i 's/_envToSet_/{{ envname }}/g' Makefile
    make setup
    source ".{{ envname }}/bin/activate"
    make install


- name: liting green app
#  become: true
  shell: |
    source ".{{ envname }}/bin/activate"
    make lint

- name: pushing green app to my repository
#  become: true
  shell: |
    ./upload_docker.sh

# run run_docker to verify the builded prediction app
#    ./run_docker.sh
