---
# - name: Setting environment variables for kubectl and getting cluster info
#   shell: |
#     newpath=$(awk '/PATH*:/ { if (!f) print $0; f = 1 }' .bash_profile)':/home/ec2-user/google-cloud-sdk/bin'
#     sed -i '/PATH*:/c\'"$newpath" .bash_profile

- name: Copying bash profile file to remote server
  ansible.builtin.copy:
    src: .bash_profile
    dest: /home/ec2-user/
