---
---
- name: copying app app.py file
  copy:
    src: {{item}}
    dest: '~/'
    mode: 0774
    with-items:
      ['run_docker.sh', 'run_kubernetes.sh', 'upload_docker.sh', 'make_prediction.sh']

- name: Installing Kubernetes with google-cloud-sdk
  shell: |
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-342.0.0-linux-x86_64.tar.gz
    tar xvfz google-cloud-sdk-342.0.0-linux-x86_64.tar.gz
    ./google-cloud-sdk/install.sh --quiet

- name: Installing kubectl and minikube and starting clusters
  shell: |
    ./google-cloud-sdk/bin/gcloud --quiet components install kubectl
    ./google-cloud-sdk/bin/gcloud --quiet components install minikube
    ./google-cloud-sdk/bin/minikube start

- name: Copying bash profile file to remote server
  ansible.builtin.copy:
    src: .bash_profile
    dest: /home/ec2-user/

- name: setting docker-hub credentials
  shell: |
    echo "${MY_DOCK_PWD}" > my_password.txt

- name: Setting environment variables for kubectl and starting cluster
  shell: |
    source "$HOME"/.bash_profile
    kubectl cluster-info
    ./run_kubernetes.sh