---
- name: copying app  file
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: 0774
  with_items:
    - run_kubernetes.sh
    - make_prediction.sh

- name: Installing Kubernetes with google-cloud-sdk
  shell: |
    echo {{ dockhub }} > my_password.txt
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-342.0.0-linux-x86_64.tar.gz
    tar xvfz google-cloud-sdk-342.0.0-linux-x86_64.tar.gz
    ./google-cloud-sdk/install.sh --quiet

- name: Installing kubectl and minikube and starting clusters
  shell: |
    ./google-cloud-sdk/bin/gcloud --quiet components install kubectl
    ./google-cloud-sdk/bin/gcloud --quiet components install minikube
    ./google-cloud-sdk/bin/minikube start

- name: Copying bash profile file to remote server
  ansible.builtin.copy:
    src: .bash_profile
    dest: /home/ec2-user/

- name: setting docker-hub credentials
  shell: |
    echo {{ dockhub }} > my_password.txt
    cat ~/my_password.txt | docker login --username eliddocker --password-stdin >> tracing.log 2>&1

- name: Setting environment variables for kubectl and starting cluster
  shell: |
    echo $HOME/.bash_profile >> tracing.log 2>&1
    source $HOME/.bash_profile >> tracing.log 2>&1
    kubectl create secret generic regcred --from-file=.dockerconfigjson=/home/ec2-user/.docker/config.json --type=kubernetes.io/dockerconfigjson >> tracing.log 2>&1
    kubectl get secrets regcred >> tracing.log 2>&1
    kubectl cluster-info >> tracing.log 2>&1
    ./run_deploykubeblueapp.sh >> tracing.log 2>&1